export const QUESTION_INFO_MAP = {
  1: { grade: "Grades.Junior", theme: "Themes.DATA_TYPES" },
  2: { grade: "Grades.Middle", theme: "Themes.ASYNC" },
  3: { grade: "Grades.Junior", theme: "Themes.OBJECTS" },
  4: { grade: "Grades.Middle", theme: "Themes.DATA_TYPES" },
  5: { grade: "Grades.Junior", theme: "Themes.OBJECTS" },
  6: { grade: "Grades.Junior", theme: "Themes.OBJECTS" },
  7: { grade: "Grades.Middle", theme: "Themes.DATA_TYPES" },
  8: { grade: "Grades.Middle", theme: "Themes.CLASSES" },
  9: { grade: "Grades.Junior", theme: "Themes.OBJECTS" },
  10: { grade: "Grades.Junior", theme: "Themes.FUNCTIONS" },
  11: { grade: "Grades.Junior", theme: "Themes.CLASSES" },
  12: { grade: "Grades.Junior", theme: "Themes.CLASSES" },
  13: { grade: "Grades.Junior", theme: "Themes.EVENTS" },
  14: { grade: "Grades.Junior", theme: "Themes.CLASSES" },
  15: { grade: "Grades.Junior", theme: "Themes.DATA_TYPES" },
  16: { grade: "Grades.Junior", theme: "Themes.BASICS" },
  17: { grade: "Grades.Junior", theme: "Themes.FUNCTIONS" },
  18: { grade: "Grades.Junior", theme: "Themes.OBJECTS" },
  19: { grade: "Grades.Junior", theme: "Themes.FUNCTIONS" },
  20: { grade: "Grades.Junior", theme: "Themes.BASICS" },
  21: { grade: "Grades.Junior", theme: "Themes.BASICS" },
  22: { grade: "Grades.Junior", theme: "Themes.STORAGE" },
  23: { grade: "Grades.Junior", theme: "Themes.BASICS" },
  24: { grade: "Grades.Junior", theme: "Themes.DATA_TYPES" },
  25: { grade: "Grades.Junior", theme: "Themes.OBJECTS" },
  26: { grade: "Grades.Junior", theme: "Themes.OBJECTS" },
  27: { grade: "Grades.Junior", theme: "Themes.BASICS" },
  28: { grade: "Grades.Junior", theme: "Themes.CLASSES" },
  29: { grade: "Grades.Middle", theme: "Themes.DATA_TYPES" },
  30: { grade: "Grades.Junior", theme: "Themes.ASYNC" },
  31: { grade: "Grades.Junior", theme: "Themes.EVENTS" },
  32: { grade: "Grades.Junior", theme: "Themes.EVENTS" },
  33: { grade: "Grades.Junior", theme: "Themes.FUNCTIONS" },
  34: { grade: "Grades.Junior", theme: "Themes.FUNCTIONS" },
  35: { grade: "Grades.Middle", theme: "Themes.BASICS" },
  36: { grade: "Grades.Junior", theme: "Themes.DATA_TYPES" },
  37: { grade: "Grades.Junior", theme: "Themes.BASICS" },
  38: { grade: "Grades.Middle", theme: "Themes.FUNCTIONS" },
  39: { grade: "Grades.Junior", theme: "Themes.DATA_TYPES" },
  40: { grade: "Grades.Junior", theme: "Themes.BASICS" },
  41: { grade: "", theme: "" },
  42: { grade: "", theme: "" },
  43: { grade: "", theme: "" },
  44: { grade: "", theme: "" },
  45: { grade: "", theme: "" },
  46: { grade: "", theme: "" },
  47: { grade: "", theme: "" },
  48: { grade: "", theme: "" },
  49: { grade: "", theme: "" },
  50: { grade: "", theme: "" },
  51: { grade: "", theme: "" },
  52: { grade: "", theme: "" },
  53: { grade: "", theme: "" },
  54: { grade: "", theme: "" },
  55: { grade: "", theme: "" },
  56: { grade: "", theme: "" },
  57: { grade: "", theme: "" },
  58: { grade: "", theme: "" },
  59: { grade: "", theme: "" },
  60: { grade: "", theme: "" },
  61: { grade: "", theme: "" },
  62: { grade: "", theme: "" },
  63: { grade: "", theme: "" },
  64: { grade: "", theme: "" },
  65: { grade: "", theme: "" },
  66: { grade: "", theme: "" },
  67: { grade: "", theme: "" },
  68: { grade: "", theme: "" },
  69: { grade: "", theme: "" },
  70: { grade: "", theme: "" },
  71: { grade: "", theme: "" },
  72: { grade: "", theme: "" },
  73: { grade: "", theme: "" },
  74: { grade: "", theme: "" },
  75: { grade: "", theme: "" },
  76: { grade: "", theme: "" },
  77: { grade: "", theme: "" },
  78: { grade: "", theme: "" },
  79: { grade: "", theme: "" },
  80: { grade: "", theme: "" },
  81: { grade: "", theme: "" },
  82: { grade: "", theme: "" },
  83: { grade: "", theme: "" },
  84: { grade: "", theme: "" },
  85: { grade: "", theme: "" },
  86: { grade: "", theme: "" },
  87: { grade: "", theme: "" },
  88: { grade: "", theme: "" },
  89: { grade: "", theme: "" },
  90: { grade: "", theme: "" },
  91: { grade: "", theme: "" },
  92: { grade: "", theme: "" },
  93: { grade: "", theme: "" },
  94: { grade: "", theme: "" },
  95: { grade: "", theme: "" },
  96: { grade: "", theme: "" },
  97: { grade: "", theme: "" },
  98: { grade: "", theme: "" },
  99: { grade: "", theme: "" },
  100: { grade: "", theme: "" },
  101: { grade: "", theme: "" },
  102: { grade: "", theme: "" },
  103: { grade: "", theme: "" },
  104: { grade: "", theme: "" },
  105: { grade: "", theme: "" },
  106: { grade: "", theme: "" },
  107: { grade: "", theme: "" },
  108: { grade: "", theme: "" },
  109: { grade: "", theme: "" },
  110: { grade: "", theme: "" },
  111: { grade: "", theme: "" },
  112: { grade: "", theme: "" },
  113: { grade: "", theme: "" },
  114: { grade: "", theme: "" },
  115: { grade: "", theme: "" },
  116: { grade: "", theme: "" },
  117: { grade: "", theme: "" },
  118: { grade: "", theme: "" },
  119: { grade: "", theme: "" },
  120: { grade: "", theme: "" },
  121: { grade: "", theme: "" },
  122: { grade: "", theme: "" },
  123: { grade: "", theme: "" },
  124: { grade: "", theme: "" },
  125: { grade: "", theme: "" },
  126: { grade: "", theme: "" },
  127: { grade: "", theme: "" },
  128: { grade: "", theme: "" },
  129: { grade: "", theme: "" },
  130: { grade: "", theme: "" },
  131: { grade: "", theme: "" },
  132: { grade: "", theme: "" },
  133: { grade: "", theme: "" },
  134: { grade: "", theme: "" },
  135: { grade: "", theme: "" },
  136: { grade: "", theme: "" },
  137: { grade: "", theme: "" },
  138: { grade: "", theme: "" },
  139: { grade: "", theme: "" },
  140: { grade: "", theme: "" },
  141: { grade: "", theme: "" },
  142: { grade: "", theme: "" },
  143: { grade: "", theme: "" },
  144: { grade: "", theme: "" },
  145: { grade: "", theme: "" },
  146: { grade: "", theme: "" },
  147: { grade: "", theme: "" },
  148: { grade: "", theme: "" },
  149: { grade: "", theme: "" },
  150: { grade: "", theme: "" },
  151: { grade: "", theme: "" },
  152: { grade: "", theme: "" },
  153: { grade: "", theme: "" },
  154: { grade: "", theme: "" },
  155: { grade: "", theme: "" },
};

export const MOCK_TYPESCRIPT = `var Grades;
(function (Grades) {
  Grades["Junior"] = "Junior";
  Grades["Middle"] = "Middle";
  Grades["Senior"] = "Senior";
})(Grades || (Grades = {}));

var Themes;
(function (Themes) {
  // Main
  Themes["BASICS"] = "BASICS";
  Themes["EVENTS"] = "EVENTS";
  Themes["CODE_QUALITY"] = "CODE_QUALITY";
  Themes["OBJECTS"] = "OBJECTS";
  Themes["DATA_TYPES"] = "DATA_TYPES";
  Themes["FUNCTIONS"] = "FUNCTIONS";
  Themes["PROTOTYPES"] = "PROTOTYPES";
  Themes["CLASSES"] = "CLASSES";
  Themes["ERRORS"] = "ERRORS";
  Themes["ASYNC"] = "ASYNC";
  Themes["GENERATORS_ITERATORS"] = "GENERATORS_ITERATORS";
  Themes["MODULES"] = "MODULES";
  // Extra
  Themes["TRICKS"] = "TRICKS";
  Themes["TYPESCRIPT"] = "TYPESCRIPT";
  Themes["ECMASCRIPT"] = "ECMASCRIPT";
})(Themes || (Themes = {}));`;
